import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import './tools/studio-presenter-macos/build-ui.mjs';
test('macOS shared DJ pad handles native state and private metadata commands', async () => {
  const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || (process.platform === 'win32' ? 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' : chromium.executablePath()),headless:true});
  const page=await browser.newPage({viewport:{width:960,height:720}});
  try {
    await page.addInitScript(()=>{window.messages=[];window.webkit={messageHandlers:{presenter:{postMessage:message=>window.messages.push(message)}}};});
    await page.goto((process.env.SLIDE_LAB_URL || 'http://127.0.0.1:5510') + '/tools/studio-presenter-macos/generated/companion.html');
    await page.waitForFunction(()=>window.messages.some(message=>message.type==='ready'));
    await page.evaluate(()=>window.receivePresenter({type:'state',index:0,total:2,notes:'Private Mac note',durationMinutes:2,editable:true,elapsed:1000,remaining:119000,budget:120000,totalBudget:180000,paused:false,width:1280,height:720,nextTitle:'Second',slides:[{title:'First',document:'<h1>First slide</h1>'},{title:'Second',document:'<h1>Second slide</h1>'}]}));
    assert.equal(await page.locator('[data-pp-notes]').inputValue(),'Private Mac note');
    assert.equal(await page.locator('[data-pp-minutes]').inputValue(),'02:00');
    assert.match(await page.locator('[data-pp-privacy]').textContent(),/Whole-display sharing can expose notes/);
    await page.locator('[data-pp-notes]').fill('Revised Mac note');
    await page.locator('[data-pp-minutes]').fill('03:30');
    await page.locator('[data-pp-minutes]').press('Tab');
    await page.getByRole('button',{name:'Pause timer',exact:true}).click();
    await page.getByRole('button',{name:'Slide overview',exact:true}).click();
    assert.equal(await page.locator('[data-pp-grid] iframe').first().getAttribute('sandbox'),'');
    await page.locator('[data-pp-jump="1"]').click();
    await page.getByRole('button',{name:'Larger notes',exact:true}).click();
    const messages=await page.evaluate(()=>window.messages);
    assert.ok(messages.some(message=>message.command==='edit'&&message.index===0&&message.key==='notes'&&message.value==='Revised Mac note'));
    assert.ok(messages.some(message=>message.command==='edit'&&message.key==='durationMinutes'&&message.value===3.5));
    assert.ok(messages.some(message=>message.command==='timer-pause'));
    assert.ok(messages.some(message=>message.command==='jump'&&message.index===1));
    assert.ok(messages.some(message=>message.type==='preference'&&message.key==='rk:presenter:notes-size'));
    await page.evaluate(()=>window.receivePresenter({type:'preferences',values:{'rk:presenter:split':'55','rk:presenter:notes-size':'24'}}));
    assert.equal(await page.locator('.pp').evaluate(element=>element.style.getPropertyValue('--pp-notes-size')),'24px');
    await page.getByRole('button',{name:'Reset notes size',exact:true}).click();
    assert.equal(await page.locator('.pp').evaluate(element=>element.style.getPropertyValue('--pp-notes-size')),'20px');
    assert.ok(await page.evaluate(()=>window.messages.some(message=>message.type==='preference'&&message.key==='rk:presenter:notes-size'&&message.value==='20')));
    await page.evaluate(()=>window.receivePresenter({type:'state',index:0,total:1,notes:'Read-only note',durationMinutes:2,editable:false,elapsed:0,remaining:120000,budget:120000,totalBudget:120000,paused:true,width:1280,height:720,slides:[{title:'First'}]}));
    assert.equal(await page.locator('[data-pp-minutes]').isDisabled(),true);
    assert.equal(await page.getByRole('button',{name:'Increase slide time',exact:true}).isDisabled(),true);
    assert.equal(await page.getByRole('button',{name:'Decrease slide time',exact:true}).isDisabled(),true);
    await page.evaluate(()=>window.receivePresenter({type:'state',index:0,total:1,notes:'Editable note',durationMinutes:240,editable:true,elapsed:0,remaining:14400000,budget:14400000,totalBudget:14400000,paused:true,width:1280,height:720,slides:[{title:'First'}]}));
    assert.equal(await page.locator('[data-pp-minutes]').inputValue(),'240:00');
    assert.equal(await page.getByRole('button',{name:'Increase slide time',exact:true}).isDisabled(),true);
    assert.equal(await page.getByRole('button',{name:'Decrease slide time',exact:true}).isEnabled(),true);
    await page.evaluate(()=>window.receivePresenter({type:'state',index:0,total:1,notes:'Local Mac note',editable:true,syncEnabled:true,conflicts:[{slideId:'first',key:'notes',local:'Local Mac note',remote:'Cloud Mac note',remoteRevision:2}],elapsed:0,remaining:0,budget:0,totalBudget:0,paused:true,width:1280,height:720,slides:[{title:'First'}]}));
    await page.locator('[data-pp-notes]').focus();
    await page.waitForFunction(()=>window.messages.some(message=>message.command==='metadata-busy'&&message.value===true));
    await page.getByRole('button',{name:'Sync private notes and names',exact:true}).click();
    await page.getByRole('button',{name:'Review conflict',exact:true}).click();
    await page.getByRole('button',{name:'Use cloud version',exact:true}).click();
    const syncMessages=await page.evaluate(()=>window.messages);
    assert.ok(syncMessages.some(message=>message.command==='metadata-sync'));
    assert.ok(syncMessages.some(message=>message.command==='metadata-resolve'&&message.value.choice==='remote'&&message.value.local==='Local Mac note'&&message.value.remote==='Cloud Mac note'));
    await page.getByRole('button',{name:'End presentation',exact:true}).click();
    assert.equal(await page.evaluate(()=>window.messages.at(-1).command),'exit');
  } finally { await browser.close(); }
});