import test from "node:test";
import assert from "node:assert/strict";
import { availableStudies, caseStudyMedia, sectionMediaUrl, sectionPlan } from "./src/js/slide-merge-sections.mjs";
import { embedDescriptor, embedAspectRatio } from "./src/js/slide-merge-embeds.mjs";
import { connectSectionAccess, sectionRuntimeData, studioSectionSources } from "./src/js/slide-studio-source.mjs";
import { sectionComponentPlan } from "./src/js/slide-merge-section-component.mjs";
const plain = value => String(value ?? "");
test('Media columns inserts retain all nested cells and original media', () => {
  const block = {type:'mediacolumns',nav:'Visual story',kicker:'Process',heading:'Decisions',items:[{label:'01',cells:[{src:'/assets/uploads/first.png',heading:'First',body:'Context'},{src:'/assets/uploads/second.png',heading:'Second',body:'Detail'}]},{label:'02',cells:[{src:'/assets/uploads/third.png'}]}]};
  const plan = sectionComponentPlan(block,plain,'media-columns');
  assert.deepEqual(plan.elements[0].customData.sectionComponent,block);
  plan.elements[0].customData.sectionComponent.items[0].cells[0].heading = 'Independent';
  assert.equal(block.items[0].cells[0].heading,'First');
  assert.deepEqual(caseStudyMedia({study:{blocks:[block]}}).map(item=>item.url),['https://media.riteshk.work/first.png','https://media.riteshk.work/second.png','https://media.riteshk.work/third.png']);
});
test('protected runtime media is temporary, validated and cancellable', async () => {
  const block = {type:'gallery',locked:true,items:[{src:'vault:private-original',caption:'Original'}]}, before = structuredClone(block);
  const signed = [];
  const source = {block,sign:async(key,options)=>{signed.push([key,options.strict]);return 'https://example.test/vault/file/original?sig=private';}};
  const runtime = await sectionRuntimeData(source);
  assert.deepEqual(signed,[['private-original',true]]);
  assert.equal(runtime.block.locked,false);
  assert.equal(runtime.media[runtime.block.items[0].src],'https://example.test/vault/file/original?sig=private');
  assert.deepEqual(block,before);
  assert.throws(()=>sectionComponentPlan(block,plain,'unsafe'),/Protected/);
  await assert.rejects(sectionRuntimeData({...source,sign:async()=> 'javascript:alert(1)'}),/not valid/);
  const controller = new AbortController();
  await assert.rejects(sectionRuntimeData({...source,sign:async()=>{controller.abort();return 'https://example.test/vault/file/original';}},controller.signal),{name:'AbortError'});
});
test('audience bridge exposes only selected cases and follows live relocking without copying data', () => {
  const source = new EventTarget(), target = new EventTarget();
  let unlocked = false;
  source.__RKStudio = {sectionAccess:()=>({active:true,unlocked}),resolveSection:()=>unlocked?{block:{type:'text',body:'Private'}}:null};
  target.RK = {};target.Event = Event;
  let updates = 0;target.addEventListener('rk:section-access',()=>updates++);
  const close = connectSectionAccess(target,['case'],source), reference = {version:1,caseStudyId:'case',sectionId:'stable'};
  assert.equal(target.RK.resolveSection(reference),null);
  unlocked = true;source.dispatchEvent(new Event('rk:section-access'));
  assert.equal(target.RK.resolveSection(reference).block.body,'Private');
  assert.equal(target.RK.resolveSection({...reference,caseStudyId:'other'}),null);
  unlocked = false;source.dispatchEvent(new Event('rk:section-access'));
  assert.equal(target.RK.resolveSection(reference),null);
  assert.equal(updates,2);
  close();close();assert.equal(target.RK.resolveSection,undefined);
  source.dispatchEvent(new Event('rk:section-access'));assert.equal(updates,3);
});
test("case-study media includes cover, overview and nested media once, excluding private content", () => {
  const work = { image:"/assets/uploads/cover.svg", study:{skim:{media:[{src:"clip.mp4",kind:"video"}]},blocks:[{items:[{src:"photo.png"},{src:"photo.png"},{src:"secret.png",locked:true}]},{locked:true,items:[{src:"hidden.png"}]},{body:"Text",url:"https://example.com/article"},{src:"/assets/protected/private.png"},{items:[{cells:[{media:{src:"deep.webp"}}]}]}]}};
  const media = caseStudyMedia(work);
  assert.deepEqual(media.map(item=>item.kind),["image","video","image","image"]);
  assert.equal(media[0].url,"https://media.riteshk.work/cover.svg");
  assert.equal(caseStudyMedia({...work,locked:true}).length,0);
  assert.equal(availableStudies({work:[{image:"cover.png"}]},true)[0].media.length,1);
});
test("section picker excludes private, locked and disabled material", () => {
  const data = {work:[{id:"public",study:{blocks:[{type:"text",body:"Hello"},{locked:true},{encStub:true},{vaultBlock:true},{off:true}]}},{locked:true,study:{blocks:[{body:"secret"}]}}]};
  assert.equal(availableStudies(data).length, 1);
  assert.equal(availableStudies(data)[0].blocks.length, 1);
  assert.throws(() => sectionPlan({locked:true,body:"secret"}, plain, 2, "section"), /not available/);
});
test("source conversion creates editable text and preserves full prose in notes", () => {
  const body = "Long content. ".repeat(100);
  const plan = sectionPlan({type:"text",heading:"Context",body}, plain, 5, "source");
  assert.equal(plan.notes, body);
  assert.ok(plan.elements[1].text.length <= 500);
  assert.ok(plan.elements[1].text.endsWith("..."));
  assert.ok(plan.elements.every(element => element.type === "text" && element.fontFamily === 5 && element.frameId === "lab-slide"));
  assert.equal(sectionPlan({type:"metrics",items:[{value:"42%",label:"Growth"}]}, plain, 5, "metric").elements[0].text,"42%");
  assert.equal(sectionPlan({type:"voices",items:[{quote:"Useful",who:"Alex"}]}, plain, 5, "quote").elements[1].text,"Alex");
});
test("media uses original source URLs and rejects executable or vault URLs", () => {
  assert.equal(sectionMediaUrl("media/original.png"), "https://riteshk.work/media/original.png");
  assert.equal(sectionMediaUrl("/assets/uploads/original.webp"), "https://media.riteshk.work/original.webp");
  assert.equal(sectionMediaUrl("https://riteshk.work/assets/uploads/original.webp?v=1"), "https://media.riteshk.work/original.webp?v=1");
  for (const value of ["javascript:alert(1)","http://example.com/image.png","https://example.com/vault/image", "https://user:pass@example.com/a", "/assets/protected/image.png", "private.enc", "rkenc:secret"]) assert.equal(sectionMediaUrl(value),null);
  const plan = sectionPlan({type:"gallery",heading:"Screens",items:[{src:"media/original.png"}]}, plain, 5, "image");
  assert.equal(plan.media.width,1100);
  assert.equal(plan.media.url,"https://riteshk.work/media/original.png");
  assert.equal(plan.elements[0].text,"Screens");
  assert.throws(() => sectionPlan({type:"unknown"}, plain, 5, "empty"), /no supported/);
});
test("media inventory excludes web embeds but retains original vector and video URLs", () => {
  const media=caseStudyMedia({study:{blocks:[{items:[{kind:"frame",src:"https://example.com/embed"},{src:"https://www.youtube.com/embed/123"},{src:"https://youtu.be/123"},{kind:"video",src:"https://media.example.com/original.mov"},{kind:"image",src:"https://media.example.com/original.svg"}]}]}});
  assert.deepEqual(media.map(item=>item.url),["https://media.example.com/original.mov","https://media.example.com/original.svg"]);
  assert.deepEqual(media.map(item=>item.kind),["video","image"]);
});

test("comparison and split media are available without losing either source", () => {
  const media = caseStudyMedia({ study: { blocks: [{ type: "compare", beforeSrc: "/assets/uploads/before.png", afterSrc: "/assets/uploads/after.png" }, { type: "split", leftImg: "left.png", rightImg: "right.png" }] } });
  assert.deepEqual(media.map(item => item.url), ["https://media.riteshk.work/before.png", "https://media.riteshk.work/after.png", "https://riteshk.work/left.png", "https://riteshk.work/right.png"]);
});

test("embedded links normalize supported providers and reject unsafe schemes", () => {
  for (const url of ['https://localhost/widget','https://127.0.0.1/widget','https://192.168.1.1/widget','https://10.0.0.1/widget']) assert.throws(()=>embedDescriptor(url), /public HTTPS/);
  assert.equal(embedDescriptor('https://platform.twitter.com/embed/Tweet.html?id=20').trusted,true);
  assert.equal(embedDescriptor('https://datawrapper.dwcdn.net/example/1/').title,'Interactive chart');
  assert.equal(embedDescriptor('https://datawrapper.dwcdn.net.evil.test/example/1/').trusted,false);
  assert.equal(embedAspectRatio('9/16'), '9/16');
  assert.equal(embedAspectRatio('1;position:fixed/1'), '3/2');
  assert.equal(embedDescriptor('https://www.youtube.com/embed/dQw4w9WgXcQ?start=120&controls=0').src, 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ?start=120&controls=0');
  assert.equal(embedDescriptor('https://www.figma.com/embed?url=https%3A%2F%2Fwww.figma.com%2Fdesign%2Fexample').src, 'https://www.figma.com/embed?url=https%3A%2F%2Fwww.figma.com%2Fdesign%2Fexample');
  assert.equal(embedDescriptor('https://www.linkedin.com/embed/feed/update/urn:li:share:12345').src, 'https://www.linkedin.com/embed/feed/update/urn:li:share:12345');
  assert.equal(embedDescriptor("https://youtu.be/dQw4w9WgXcQ").src,"https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ");
  assert.equal(embedDescriptor("https://vimeo.com/12345").src,"https://player.vimeo.com/video/12345");
  assert.equal(embedDescriptor("https://example.com/video.mp4").kind,"video");
  assert.equal(embedDescriptor("https://example.com/image.png").kind,"image");
  assert.equal(embedDescriptor("https://example.com/document.pdf").title,"PDF document");
  assert.equal(embedDescriptor("https://example.com/podcast.mp3").kind,"audio");
  assert.equal(embedDescriptor("https://x.com/example/status/12345?s=20").src,"https://platform.twitter.com/embed/Tweet.html?id=12345");
  assert.equal(embedDescriptor("https://www.instagram.com/p/ABC_123/").src,"https://www.instagram.com/p/ABC_123/embed/");
  assert.equal(embedDescriptor("https://www.tiktok.com/@example/video/123456").src,"https://www.tiktok.com/player/v1/123456");
  assert.equal(embedDescriptor("https://open.spotify.com/track/ABC123").src,"https://open.spotify.com/embed/track/ABC123");
  assert.match(embedDescriptor("https://www.linkedin.com/posts/example_activity-123456-test").src,/urn:li:activity:123456$/);
  assert.equal(embedDescriptor("https://x.com.evil.test/example/status/12345").title,"Embedded content");
  for (const value of ["javascript:alert(1)","data:text/html,test","file:///test","http://example.com","https://user:password@example.com","not a URL"]) assert.throws(()=>embedDescriptor(value));
});
test("section inserts opt into locked references without widening media or default AI sources", async () => {
  const source = {work:[{id:'case',study:{blocks:[{type:'text',body:'Public'},{type:'gallery',locked:true,vaultBlock:'opaque-key'},{type:'text',off:true,locked:true}]}}]};
  const values = new Map([['rk:content:draft',JSON.stringify(source)]]);
  const environment = {localStorage:{getItem:key=>values.get(key),setItem:(key,value)=>values.set(key,value)},dispatchEvent(){}};
  const prepared = await studioSectionSources(undefined,'case',environment);
  const sectionId = prepared.work[0].study.blocks[1].sectionId;
  assert.ok(sectionId);
  assert.equal(source.work[0].study.blocks[1].sectionId,undefined);
  assert.equal(availableStudies(prepared)[0].blocks.length,1);
  assert.equal(availableStudies(prepared,false,true)[0].blocks.length,2);
  const plan = sectionComponentPlan(prepared.work[0].study.blocks[1],plain,'insert',{caseStudyId:'case'});
  assert.equal(plan.elements[0].customData.sectionReference.sectionId,sectionId);
  assert.doesNotMatch(JSON.stringify(plan),/opaque-key/);
  prepared.work[0].study.blocks.reverse();
  values.set('rk:content:draft',JSON.stringify(prepared));
  const reopened = await studioSectionSources(undefined,'case',environment);
  assert.equal(reopened.work[0].study.blocks.find(block=>block.vaultBlock).sectionId,sectionId);
  const previous = values.get('rk:content:draft');
  environment.localStorage.setItem = () => {throw new Error('Storage full');};
  const changed = JSON.parse(previous);delete changed.work[0].study.blocks[1].sectionId;
  values.set('rk:content:draft',JSON.stringify(changed));
  await assert.rejects(studioSectionSources(undefined,'case',environment),/Storage full/);
  assert.equal(values.get('rk:content:draft'),JSON.stringify(changed));
});